NameError: name 'alist' is not defined

In [4]:
alist=[1,2,3,4,5]

In [2]:
import numpy as np


In [8]:
numbers = np.array([1,2,3,4,5,6,7])

m=numbers+numbers

In [9]:
def squares(values):
    result = []
    for v in values:
        result.append(v*v)
    return result    

In [10]:
to_square = range(100000)

In [11]:
%timeit squares(to_square)

17 ms ± 72.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [12]:
array_to_square = np.arange(0,100000)


In [13]:
%timeit array_to_square**2

157 µs ± 146 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [14]:
a = np.array([33,44,55])

In [15]:
a

array([33, 44, 55])

In [16]:
type(a)

numpy.ndarray

In [17]:
np.size(a)

3

In [18]:
len(a)

3

In [20]:
a2 = np.array([1,2,3.5,4,5],dtype=int)

In [31]:
_2Darray = np.array([[1,2,4,3],[5,6,7,8],[2,3,4,5],[1,2,3,4]])

In [32]:
_2Darray

array([[1, 2, 4, 3],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [1, 2, 3, 4]])

In [27]:
 np.size(_2Darray)

16

In [28]:
len(_2Darray)

4

In [33]:
_2Darray = np.array([[1,2,4,3],[5,6,7,8],[2,3,4,5],[1,2,3]])

In [34]:
_2Darray

array([list([1, 2, 4, 3]), list([5, 6, 7, 8]), list([2, 3, 4, 5]),
       list([1, 2, 3])], dtype=object)

In [35]:
_2Darray = np.arange(25)

In [36]:
_2Darray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
_2Darray = np.arange(30).reshape(6,5)

In [41]:
_2Darray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [4]:
_2Darray = np.random.randn(30).reshape(6,5)
_2Darray

array([[ 0.02018749,  0.33415235, -2.14883504,  0.23797937, -0.73892846],
       [-0.03731249,  0.17915074,  0.02561395,  0.47726494,  0.12110342],
       [ 0.05754153, -0.68925449,  0.47759876,  0.25951658, -1.43389004],
       [-1.18847444,  0.09286648,  0.20251168, -0.18016549, -0.51588568],
       [ 1.08106799,  1.81257724,  1.83159339, -1.96604901, -0.89686216],
       [ 0.2941167 , -0.79222806,  0.63284098,  0.09685789,  0.41897786]])

In [5]:
_2Darray = np.arange(30).reshape(6,5)
_2Darray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [6]:
_2Darray[3,4] # particular cell selected.... 3rd row and 4th column

19

In [12]:
_2Darray[5,4]

29

In [13]:
_2Darray[1,] # complete row selection 

array([5, 6, 7, 8, 9])

In [15]:
_2Darray[1:3, 1:3] #slicing

array([[ 6,  7],
       [11, 12]])

In [16]:
_2Darray[1:3, 1:3].ndim  # to get to know the dimension

2

In [22]:
_2Darray[1:4, 1:2]

array([[ 6],
       [11],
       [16]])

In [23]:
_2Darray[1:3, 3:5]

array([[ 8,  9],
       [13, 14]])

In [24]:
_2Darray[:,4] # selection complete column

array([ 4,  9, 14, 19, 24, 29])

In [25]:
_2Darray[:,1]

array([ 1,  6, 11, 16, 21, 26])

In [26]:
_2Darray[4,] # selection

array([20, 21, 22, 23, 24])

In [27]:
_2Darray[5:6,0:6]

array([[25, 26, 27, 28, 29]])

In [28]:
p=_2Darray[4,:] # slicing

In [29]:
p

array([20, 21, 22, 23, 24])

In [30]:
d3 = np.arange(100).reshape(5,5,4)

In [31]:
d3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

In [32]:
d3[2:4,2:4,1:4]

array([[[49, 50, 51],
        [53, 54, 55]],

       [[69, 70, 71],
        [73, 74, 75]]])

In [33]:
a= np.array([[[[[[[[[[10]]]]]]]]]])

In [34]:
a

array([[[[[[[[[[10]]]]]]]]]])

In [35]:
a.ndim

10

In [36]:
a=np.arange(5)

In [37]:
a

array([0, 1, 2, 3, 4])

In [40]:
a>3

array([False, False, False, False,  True])

In [42]:
np.sum(a>1)

3

In [43]:
a=np.arange(30).reshape(5,6)

In [44]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [45]:
a[[1,3,4],:]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [3]:
z=np.arange(1,10)

NameError: name 'np' is not defined

In [4]:
import numpy as np

In [5]:
z=np.arange(1,10)
z

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
z.cumsum(), z.cumprod()

(array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32),
 array([     1,      2,      6,     24,    120,    720,   5040,  40320,
        362880], dtype=int32))

In [7]:
a = np.arange(12).reshape(3,4)

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
np.hsplit(a,4)

[array([[0],
        [4],
        [8]]), array([[1],
        [5],
        [9]]), array([[ 2],
        [ 6],
        [10]]), array([[ 3],
        [ 7],
        [11]])]

In [16]:
np.hsplit(a,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

# 19-Aug-19

In [2]:
import numpy as np

In [6]:
a = np.arange(12).reshape(3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [4]:
A

NameError: name 'A' is not defined

In [5]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
[1:3, 1:3]

In [8]:
a = np.arange(9).reshape(3,3)

In [9]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
a[:2, 1:]

array([[1, 2],
       [4, 5]])

In [12]:
a[:1, 1:]

array([[1, 2]])

In [14]:
a[:2, 2:]

array([[2],
       [5]])

In [15]:
names = np.array(['Bob','Joe', 'Will','Bob', 'Will', 'Joe','Joe'])

In [16]:
data = np.random.rand(7,4)

In [17]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [18]:
data

array([[0.97198559, 0.32630562, 0.60911467, 0.39604205],
       [0.15752473, 0.71514365, 0.63801845, 0.21669059],
       [0.35092306, 0.47434019, 0.003334  , 0.37864055],
       [0.16060999, 0.39806816, 0.77513277, 0.27655322],
       [0.41141818, 0.17434612, 0.9946959 , 0.32228255],
       [0.89317618, 0.59768626, 0.17617423, 0.21478777],
       [0.76606342, 0.70405264, 0.30332168, 0.59880731]])

In [19]:
names =='Bob'

array([ True, False, False,  True, False, False, False])

In [20]:
data[names == "Bob"]

array([[0.97198559, 0.32630562, 0.60911467, 0.39604205],
       [0.16060999, 0.39806816, 0.77513277, 0.27655322]])

In [21]:
data [names == "Bob", 2:]

array([[0.60911467, 0.39604205],
       [0.77513277, 0.27655322]])

In [22]:
data [names == "Bob", 3]

array([0.39604205, 0.27655322])

In [24]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [26]:
data[~(names=="Bob")]

array([[0.15752473, 0.71514365, 0.63801845, 0.21669059],
       [0.35092306, 0.47434019, 0.003334  , 0.37864055],
       [0.41141818, 0.17434612, 0.9946959 , 0.32228255],
       [0.89317618, 0.59768626, 0.17617423, 0.21478777],
       [0.76606342, 0.70405264, 0.30332168, 0.59880731]])

# transposing

In [30]:
arr = np.arange(16).reshape(2,2,4)

In [31]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

AttributeError: 'numpy.ndarray' object has no attribute 't'

In [32]:
mat1 = np.arange(12).reshape(3,4)
mat2 = np.array([[4,5,6,7],[3,4,5,6],[9,7,6,5]])

In [33]:
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
mat2

array([[4, 5, 6, 7],
       [3, 4, 5, 6],
       [9, 7, 6, 5]])

In [35]:
mat1 * mat2

array([[ 0,  5, 12, 21],
       [12, 20, 30, 42],
       [72, 63, 60, 55]])

In [36]:
mat3=np.array([[4,5,6,7],[3,4,5,6],[9,7,6,5],[3,2,6,8]])

In [37]:
mat1@mat3

array([[ 30,  24,  35,  40],
       [106,  96, 127, 144],
       [182, 168, 219, 248]])

In [38]:
# mat.1dot(mat3)
np.dot(mat1,mat3)

array([[ 30,  24,  35,  40],
       [106,  96, 127, 144],
       [182, 168, 219, 248]])